# runtime: nodejs16

# instance_class: F2

# env_variables:
#   HOST: "0.0.0.0"
#   NODE_ENV: "production"
#   DATABASE_NAME: "strapidb"
#   DATABASE_USERNAME: "postgres"
#   DATABASE_PASSWORD: "postgres"
#   INSTANCE_CONNECTION_NAME: "strapi-386902:us-central1:strapidb"

# beta_settings:
#   cloud_sql_instances: "strapi-386902:us-central1:strapidb"
